# Generated by Django 5.2.5 on 2025-08-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodio',
            options={'ordering': ['-data_inizio'], 'verbose_name': 'Episodio', 'verbose_name_plural': 'Episodi'},
        ),
        migrations.AlterModelOptions(
            name='farmaco',
            options={'verbose_name': 'Farmaco', 'verbose_name_plural': 'Farmaci'},
        ),
        migrations.AlterModelOptions(
            name='letto',
            options={'verbose_name': 'Letto', 'verbose_name_plural': 'Letti'},
        ),
        migrations.AlterModelOptions(
            name='orariodose',
            options={'verbose_name': 'OrarioDose', 'verbose_name_plural': 'OrarioDosi'},
        ),
        migrations.AlterModelOptions(
            name='parametrovitale',
            options={'ordering': ['-rilevato_il'], 'verbose_name': 'ParametroVitale', 'verbose_name_plural': 'ParametriVitali'},
        ),
        migrations.AlterModelOptions(
            name='prescrizione',
            options={'verbose_name': 'Prescrizione', 'verbose_name_plural': 'Prescrizioni'},
        ),
        migrations.AlterModelOptions(
            name='rigaprescrizione',
            options={'verbose_name': 'RigaPrescrizione', 'verbose_name_plural': 'RigaPrescrizioni'},
        ),
        migrations.AlterModelOptions(
            name='somministrazione',
            options={'verbose_name': 'Somministrazione', 'verbose_name_plural': 'Somministrazioni'},
        ),
        migrations.AlterModelOptions(
            name='stanza',
            options={'verbose_name': 'Stanza', 'verbose_name_plural': 'Stanze'},
        ),
        migrations.AlterModelOptions(
            name='voceigiene',
            options={'verbose_name': 'VoceIgiene', 'verbose_name_plural': 'VociIgiene'},
        ),
        migrations.RemoveIndex(
            model_name='farmaco',
            name='core_farmac_nome_3436c3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='farmaco',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='letto',
            unique_together=set(),
        ),
    ]
