# Generated by Django 5.2.5 on 2025-08-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_episodio_options_alter_farmaco_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documenti'},
        ),
        migrations.AddField(
            model_name='episodio',
            name='provenienza',
            field=models.CharField(choices=[('DOM', 'Domicilio'), ('OSP', 'Struttura Ospedaliera'), ('SOC', 'Servizi Sociali'), ('ALT', 'Altro')], default='DOM', max_length=3, verbose_name='Provenienza'),
            preserve_default=False,
        ),
    ]
