# Generated by Django 5.2.5 on 2025-08-17 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_documento_options_episodio_provenienza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioIgiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rilevato_il', models.DateTimeField()),
                ('evento', models.CharField(choices=[('DOCCIA', 'Doccia'), ('DOCCIA_CAPELLI', 'Doccia + Capelli')], max_length=20)),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diari_igiene', to='core.paziente')),
            ],
            options={
                'verbose_name': 'DiarioIgiene',
                'verbose_name_plural': 'DiarioIgiene',
                'ordering': ['-rilevato_il'],
                'indexes': [models.Index(fields=['paziente', 'rilevato_il'], name='core_diario_pazient_a825c6_idx')],
            },
        ),
    ]
