# Generated by Django 5.1.6 on 2025-08-19 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diarioigiene'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmaco',
            name='forma',
            field=models.CharField(blank=True, choices=[('bust', 'Bustina'), ('cpr', 'Compressa'), ('F', 'Fiala'), ('FL', 'Flacone'), ('gtt', 'Gocce')], help_text='Forma farmaceutica (es. Bustina, Compressa, Fiala, Flacone, Gocce).', max_length=10),
        ),
        migrations.AlterField(
            model_name='rigaprescrizione',
            name='via',
            field=models.CharField(choices=[('Orale', 'Orale'), ('IM', 'IM'), ('EV', 'EV'), ('SC', 'SC'), ('SL', 'Sublinguale'), ('TOP', 'Topica'), ('SNG', 'Sondino naso gastrico'), ('PEG', 'PEG'), ('DEP', 'DEP')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='farmaco',
            unique_together={('nome', 'forma', 'forza_val', 'forza_udm')},
        ),
        migrations.AddIndex(
            model_name='farmaco',
            index=models.Index(fields=['nome'], name='core_farmac_nome_3436c3_idx'),
        ),
    ]
