# Generated by Django 5.2.5 on 2025-08-22 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_allergia_contattoemergenza_recapitocontatto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=80)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('PUBB', 'Pubblicato'), ('ARCH', 'Archiviato')], default='BOZZA', max_length=5)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('aggiornato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggiornato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creato_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Periodo menu',
                'verbose_name_plural': 'Periodi menu',
                'ordering': ['-data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='MenuPasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('pasto', models.CharField(choices=[('COLAZ', 'Colazione'), ('MEREN', 'Merenda'), ('PRANZ', 'Pranzo'), ('SPUN', 'Spuntino'), ('CENA', 'Cena')], max_length=5)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('aggiornato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggiornato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasti', to='core.menuperiodo')),
            ],
            options={
                'verbose_name': 'Menu del pasto',
                'verbose_name_plural': 'Menu dei pasti',
                'ordering': ['data', 'pasto'],
            },
        ),
        migrations.CreateModel(
            name='Pietanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('PRIMO', 'Primo'), ('SECON', 'Secondo'), ('CONT', 'Contorno'), ('UNICO', 'Piatto unico'), ('FRUTT', 'Frutta'), ('DOLCE', 'Dolce'), ('BEV', 'Bevanda'), ('ALTRO', 'Altro')], default='ALTRO', max_length=6)),
                ('tag_dieta', models.CharField(blank=True, max_length=120, verbose_name='Tag dieta (es. senza sale, veg, senza lattosio)')),
                ('allergeni_note', models.CharField(blank=True, max_length=200, verbose_name='Allergeni/Note')),
                ('aggiornato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggiornato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creato_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pietanza',
                'verbose_name_plural': 'Pietanze',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VoceMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('descrizione_libera', models.CharField(blank=True, max_length=150)),
                ('ordine', models.PositiveSmallIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('aggiornato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggiornato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('pasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='core.menupasto')),
                ('pietanza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pietanza')),
            ],
            options={
                'verbose_name': 'Voce di menu',
                'verbose_name_plural': 'Voci di menu',
                'ordering': ['pasto__data', 'pasto__pasto', 'ordine', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='menuperiodo',
            index=models.Index(fields=['data_inizio', 'data_fine', 'stato'], name='core_menupe_data_in_a5618f_idx'),
        ),
        migrations.AddIndex(
            model_name='menupasto',
            index=models.Index(fields=['data', 'pasto'], name='core_menupa_data_727158_idx'),
        ),
        migrations.AddIndex(
            model_name='menupasto',
            index=models.Index(fields=['periodo'], name='core_menupa_periodo_ca6984_idx'),
        ),
        migrations.AddConstraint(
            model_name='menupasto',
            constraint=models.UniqueConstraint(fields=('data', 'pasto'), name='unico_menu_pasto_per_data'),
        ),
        migrations.AddIndex(
            model_name='pietanza',
            index=models.Index(fields=['nome', 'categoria'], name='core_pietan_nome_03ae48_idx'),
        ),
        migrations.AddIndex(
            model_name='vocemenu',
            index=models.Index(fields=['pasto', 'ordine'], name='core_voceme_pasto_i_8afb98_idx'),
        ),
        migrations.AddConstraint(
            model_name='vocemenu',
            constraint=models.CheckConstraint(condition=models.Q(('pietanza__isnull', False), ('descrizione_libera__gt', ''), _connector='OR'), name='voce_menu_pietanza_o_testo'),
        ),
    ]
