# Generated by Django 5.2.5 on 2025-08-22 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_menuperiodo_menupasto_pietanza_vocemenu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('cognome', models.CharField(max_length=80)),
                ('ruolo', models.CharField(choices=[('OSS', 'OSS'), ('INF', 'Infermiere'), ('CUOCO', 'Cuoco'), ('PUL', 'Pulizie'), ('COORD', 'Coordinatore'), ('AMM', 'Amministrativo'), ('ALTRO', 'Altro')], default='OSS', max_length=6)),
                ('attivo', models.BooleanField(default=True)),
                ('aggiornato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggiornato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('utente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profilo_dipendente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PianoTurniPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=80)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('PUBB', 'Pubblicato'), ('ARCH', 'Archiviato')], default='BOZZA', max_length=5)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('aggiornato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggiornato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creato_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Periodo turni',
                'verbose_name_plural': 'Periodi turni',
                'ordering': ['-data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='TurnoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('codice', models.CharField(max_length=12, unique=True)),
                ('nome', models.CharField(max_length=40)),
                ('ora_inizio', models.TimeField(blank=True, null=True)),
                ('ora_fine', models.TimeField(blank=True, null=True)),
                ('is_riposo', models.BooleanField(default=False)),
                ('ordine', models.PositiveSmallIntegerField(default=1)),
                ('aggiornato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggiornato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creato_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo turno',
                'verbose_name_plural': 'Tipi turno',
                'ordering': ['ordine', 'codice'],
            },
        ),
        migrations.CreateModel(
            name='AssegnazioneTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('aggiornato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggiornato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creato_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni', to='core.dipendente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='core.pianoturniperiodo')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni', to='core.turnotipo')),
            ],
            options={
                'verbose_name': 'Assegnazione turno',
                'verbose_name_plural': 'Assegnazioni turni',
                'ordering': ['data', 'turno__ordine', 'dipendente__cognome'],
            },
        ),
        migrations.AddIndex(
            model_name='dipendente',
            index=models.Index(fields=['cognome', 'nome'], name='core_dipend_cognome_95ad90_idx'),
        ),
        migrations.AddIndex(
            model_name='dipendente',
            index=models.Index(fields=['attivo', 'ruolo'], name='core_dipend_attivo_dfa9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='pianoturniperiodo',
            index=models.Index(fields=['data_inizio', 'data_fine', 'stato'], name='core_pianot_data_in_dbfd44_idx'),
        ),
        migrations.AddIndex(
            model_name='assegnazioneturno',
            index=models.Index(fields=['periodo', 'data'], name='core_assegn_periodo_9d7554_idx'),
        ),
        migrations.AddIndex(
            model_name='assegnazioneturno',
            index=models.Index(fields=['dipendente', 'data'], name='core_assegn_dipende_9b32bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='assegnazioneturno',
            constraint=models.UniqueConstraint(fields=('periodo', 'data', 'dipendente'), name='un_turno_per_giorno_per_dipendente'),
        ),
    ]
