# Generated by Django 5.2.5 on 2025-08-29 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dipendente_pianoturniperiodo_turnotipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='allergia',
            name='allergia_coerenza_categoria',
        ),
        migrations.AddConstraint(
            model_name='allergia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('categoria', 'FARMACO'), models.Q(('farmaco__isnull', False), ('sostanza_libera__gt', ''), _connector='OR')), models.Q(('categoria__in', ['ALIMENTARE', 'ALTRO']), ('sostanza_libera__gt', '')), _connector='OR'), name='allergia_coerenza_categoria'),
        ),
    ]
