# Generated by Django 5.2.5 on 2025-08-30 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_allergia_allergia_coerenza_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescrizione',
            name='medico',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescrizioni_medico', to=settings.AUTH_USER_MODEL),
        ),
    ]
