# Generated by Django 5.2.5 on 2025-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_prescrizione_medico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dipendente',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'Personale', 'verbose_name_plural': 'Personale'},
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ruolo',
            field=models.CharField(choices=[('OSS', 'OSS'), ('INF', 'Infermiere'), ('CUOCO', 'Cuoco'), ('PUL', 'Pulizie'), ('COORD', 'Coordinatore'), ('AMM', 'Amministrativo'), ('VOL', 'Volontario'), ('ALTRO', 'Altro')], default='OSS', max_length=6),
        ),
    ]
